export const api = {
  contacts: {
    listContacts: {} as any,
    createContact: {} as any,
    getContactDetails: {} as any,
  },
  sites: {
    listSites: {} as any,
    createSite: {} as any,
  },
  provenance: {
    getProvenanceForUser: {} as any,
    listProvenanceBySite: {} as any,
  },
  rituals: {
    getRituals: {} as any,
    createBipsRitual: {} as any,
  },
  hud: {
    getHudContactsView: {} as any,
    getHudSitesView: {} as any,
    getHudProvenanceView: {} as any,
    getHudRitualsView: {} as any,
  },
  messages: {
    getConversations: {} as any,
    sendMessage: {} as any,
    getOrCreateConversation: {} as any,
    getConversation: {} as any,
    markAsRead: {} as any,
  },
  users: {
    ensureUser: {} as any,
    getAllUsers: {} as any,
  },
  cards: {
    getAdminCards: {} as any,
    getCardsForUser: {} as any,
    triggerCardEvent: {} as any,
    deleteCard: {} as any,
    createCard: {} as any,
  },
  location: {
    listLocations: {} as any,
    getLatestLocation: {} as any,
  },
  leach: {
    createWorkboardItem: {} as any,
    updateWorkboardItem: {} as any,
    getWorkboardItems: {} as any,
    deleteWorkboardItem: {} as any,
    createSyncRitual: {} as any,
    updateSyncRitual: {} as any,
    getSyncRituals: {} as any,
    deleteSyncRitual: {} as any,
    startSession: {} as any,
    endSession: {} as any,
    getActiveSession: {} as any,
  },
  analytics: {
    trackEvent: {} as any,
    listEventsBySite: {} as any,
    getEventStats: {} as any,
    getAllSitesStats: {} as any,
    getTopPages: {} as any,
    getTopReferrers: {} as any,
  },
  ops: {
    listAlerts: {} as any,
    createAlert: {} as any,
    resolveAlert: {} as any,
    deleteAlert: {} as any,
    listNotes: {} as any,
    createNote: {} as any,
    deleteNote: {} as any,
    saveSnapshot: {} as any,
    listSnapshots: {} as any,
    getOpsSummary: {} as any,
    listPushLog: {} as any,
    dispatchAlertPush: {} as any,
    logPushDispatch: {} as any,
    triggerAutoSnapshot: {} as any,
  },
} as const;
